#!/bin/bash -ex
#
# MIT License
#
# Copyright (c) 2023 Vincent Smeets
#
EXIT_SUCCESS=0
EXIT_FAILURE=1
EXIT_INVALIDARGUMENT=2
EXIT_NOTIMPLEMENTED=3
EXIT_NOPERMISSION=4

packageName="dsmr-server"
progName=$(basename "$0")

defaultFile="/etc/default/$packageName"
[[ -r $defaultFile ]] && . "$defaultFile"

parsedArgs=$(getopt \
	--name "$progName" \
	--options 'l:p:t:' \
	--longoptions 'log-directory:' \
	--longoptions 'port:' \
	--longoptions 'terminal:' \
	-- "$@")
eval set -- "$parsedArgs"
unset parsedArgs

while true
do
	case "$1" in
	-l | --log-directory)
		logDirectory="$2"
		shift 2
		;;
	-p | --port)
		port="$2"
		shift 2
		;;
	-t | --terminal)
		terminal="$2"
		shift 2
		;;
	--)
		break
		;;
	*)
		echo "Internal error!" >&2
		exit $EXIT_NOTIMPLEMENTED
		;;
	esac
done
[[ -n $terminal ]] || { echo "No terminal defined!" >&2 && exit $EXIT_INVALIDARGUMENT; }
[[ -n $logDirectory ]] || logDirectory="${logDirectories[$terminal]}"
[[ -n $logDirectory && -d $logDirectory ]] || { echo "No log directory defined!" >&2 && exit $EXIT_INVALIDARGUMENT; }
[[ -n $port ]] || port="${ports[$terminal]}"
[[ -n $port ]] || { echo "No port defined!" >&2 && exit $EXIT_INVALIDARGUMENT; }

while true
do
	readerPid=$(pgrep --terminal "$terminal")
	logFile=$(ls -rt "$logDirectory"/*.log | tail --lines=1)
	[[ -r $logFile ]] || { echo "Can't read the log file:" "$logFile" >&2 && exit $EXIT_NOPERMISSION; }

	echo "Providing file:" "$logFile"
	tail --follow --pid="$readerPid" "$logFile" | nc -l -p "$port" -v -w 10 || true
done
